language: php

php:
  - 7.2

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -u root -e "CREATE DATABASE IF NOT EXISTS testing;
                      USE testing;
                      CREATE TABLE IF NOT EXISTS mdl_role_assignments (
                        id INT AUTO_INCREMENT PRIMARY KEY,
                        roleid INT,
                        contextid INT,
                        userid INT
                      )  ENGINE=InnoDB;"
  - composer self-update
  - composer install --no-interaction
  - npm install -g npm@latest
  - npm i -g npm
  - npm install
  - php artisan key:generate
  - php artisan storage:link
  - php artisan config:cache
  - php artisan migrate
  - php artisan db:seed
  - php artisan RosterUpdate:UpdateRoster
  - php artisan OnlineControllers:GetControllers
  - php artisan Overflights:GetOverflights
  - if find . -name "*.php" ! -path "./vendor/*" -exec php -l {} \; | grep -v "No syntax errors detected"; then exit 1; fi

script:
  - vendor/bin/phpunit
